[project]
name = "pv-232-lab-1"
version = "0.1.0"
description = "Лабораторная работа №1 по тестированию ПО"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.uv]
package = false
